<link href="//cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<link href="//cdn.bootcss.com/bootstrap-table/1.11.1/bootstrap-table.min.css" rel="stylesheet">
<link href="//cdn.bootcss.com/bootstrap-select/1.12.3/css/bootstrap-select.min.css" rel="stylesheet">
<link href="//cdn.bootcss.com/bootstrap-switch/3.3.4/css/bootstrap3/bootstrap-switch.min.css" rel="stylesheet">
<link href="//cdn.bootcss.com/bootstrap-slider/9.8.1/css/bootstrap-slider.min.css" rel="stylesheet">
<link href="//cdn.bootcss.com/sweetalert/1.1.3/sweetalert.min.css" rel="stylesheet">
<link rel="stylesheet" href="../../static/plugins/HoorayLibs/hooraylibs.css">
<link rel="stylesheet" href="../../static/plugins/webuploader-0.1.5/webuploader.css">
<link rel="stylesheet" href="../../static/plugins/Waves-0.7.5/dist/waves.min.css">
<link rel="stylesheet" href="../../static/css/sys.css">