<link rel="stylesheet" href="../../static/css/globle.css">
<link rel="stylesheet" href="../../static/plugins/HoorayLibs/hooraylibs.css">
<link rel="stylesheet" href="../../static/plugins/bootstrap-3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="../../static/plugins/bootstrap-table-1.11.1/dist/bootstrap-table.min.css">
<link rel="stylesheet" href="../../static/plugins/bootstrap-select-1.12.2/dist/css/bootstrap-select.min.css">
<link rel="stylesheet" href="../../static/plugins/bootstrap-switch-3.3.4/dist/css/bootstrap3/bootstrap-switch.min.css">
<link rel="stylesheet" href="../../static/plugins/artDialog-7.0.0/css/ui-dialog.css">
<link rel="stylesheet" href="../../static/plugins/sweetalert-1.1.1/dist/sweetalert.css">
<link rel="stylesheet" href="../../static/plugins/webuploader-0.1.5/webuploader.css">