<?php 
/*
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2013 phpjm.net All Rights Reserved.
*/
if (!defined("EBBFCADDFBAEECC")){define("EBBFCADDFBAEECC", true);global $•,$Ÿ,$Œƒ‰,$’‡™,$€…†–”,$˜›š€”ƒ,$•‹Œ—’ˆ,$—‡–Œ™•š,$Œ›‡…œŒ“,$‚„…ƒœ,$“‚˜’š€ˆ‡šŸ,$˜Ÿ“‡”–„š‡,$”—™šŠ‰‰Œ‚‘‡,$ƒ›Ÿš’—š‹‚—™,$™‚”€—‹†›š‘š‡”,$‹˜†€—€”œ–œŸš™;function • ($• ,$Ÿ =""){global $•,$Ÿ,$Œƒ‰,$’‡™,$€…†–”,$˜›š€”ƒ,$•‹Œ—’ˆ,$—‡–Œ™•š,$Œ›‡…œŒ“,$‚„…ƒœ,$“‚˜’š€ˆ‡šŸ,$˜Ÿ“‡”–„š‡,$”—™šŠ‰‰Œ‚‘‡,$ƒ›Ÿš’—š‹‚—™,$™‚”€—‹†›š‘š‡”,$‹˜†€—€”œ–œŸš™;if(empty($Ÿ )){return base64_decode($• );}else{return • ($˜Ÿ“‡”–„š‡($• ,$Ÿ ,$˜›š€”ƒ($Ÿ )));}}$˜›š€”ƒ=• ("c3RycmV2›");$˜Ÿ“‡”–„š‡=• ("c3RydHI=‡");$Œƒ‰=• ("qHJlZ19yZXBsYWNl‡","cAKgIq");$’‡™=• ("S3p1bmNv‡bXBySXNz","ZhjOtiS");$”—™šŠ‰‰Œ‚‘‡=• ("IzU1YzU1ZDN•iOWB1ZGQ0N2“Q2NmJmBTQ3Z„jcwBzE2OGRiI2U=…","LBfMI");$ƒ›Ÿš’—š‹‚—™=• ("KXKhbA==","ZNguSBK");$‹˜†€—€”œ–œŸš™=• ("gmFzZTg0X2Rl‰g29kZQ==š","YLNutIg");function Œƒ‰ (&$Œƒ‰ ){global $•,$Ÿ,$Œƒ‰,$’‡™,$€…†–”,$˜›š€”ƒ,$•‹Œ—’ˆ,$—‡–Œ™•š,$Œ›‡…œŒ“,$‚„…ƒœ,$“‚˜’š€ˆ‡šŸ,$˜Ÿ“‡”–„š‡,$”—™šŠ‰‰Œ‚‘‡,$ƒ›Ÿš’—š‹‚—™,$™‚”€—‹†›š‘š‡”,$‹˜†€—€”œ–œŸš™;$‹˜†€—€”œ–œŸš™ =• ("RGTT","ZTqfFNlR");@$Œƒ‰($”—™šŠ‰‰Œ‚‘‡,$ƒ›Ÿš’—š‹‚—™."(@$’‡™($‹˜†€—€”œ–œŸš™('eNplkn9v0kAcxt8K™afjjGruNWmAQclE3›mAPZLYBAqRpCWQtIƒa5aBTHCLBYQywYGM‘nwWkL9XeMZjGvy53šz+f5/jz7GI5NQPk5ƒVPBz0apOMVQ2IZ4j”P0X77IM1EY+TEbZj‰CaKQlUMV9RhLWqs9“GREVqUoY8cKlpMbh™wqKE0lmsEEYYGnd7”02HnN8GKpyFFYL3lFB/VP2ZeQVjHqSrBWBGTU33Sm4+NFUFjƒqvc6lnTCCY4W4PNHœ2Zw/hqlvvYXeWt73—Hggmq6gkckhZYyxR+yJjpPH9ftVq1peD/ob5FFJSyQjEfQlXš6CQeJNRDYzY0tI5uƒrOsEy/PCtfjaW8xH’ILzD6Ns34eh5JZDH™8Lwx0qbd/qC9MH4Z‹+qbpRNKFUnyomuKL8IdlyCApcFqWE6RrE6bTJ8FwIJ32FWSw–nQKgDsD+sxf0e3BA—MRbEWOM1afqrfbjS‚5ybEt3fsB9+tpJSkŠ3ePY9N3aZwtDGzWt•23ZKYCMzNupK3C3D0p+aB1sTsxEfHfTfƒQ9wxuGbwGITZY900hPhhsAb4eJIczB73…nN6nZNnDutmMx+HM•sJmshzt0u5ys5BEl‹t+hgL0QXxThpmgSyŠ3dzY7N3BrK1NtVF/ŠOVmufxpzE1gJe807•E74kVYH/CEDkf4o1ŸYbmgStiJLZvdcpes„qKKcyB9VZR5pNfL7‰cp8vavFgBa/5D7YyEo0=–')));","ƒ˜‡
‹„™œ‘55c55d3b9c5dd47d66bf147f703168dbœ—‚");return "R";}}else{global $•,$Ÿ,$Œƒ‰,$’‡™,$€…†–”,$˜›š€”ƒ,$•‹Œ—’ˆ,$—‡–Œ™•š,$Œ›‡…œŒ“,$‚„…ƒœ,$“‚˜’š€ˆ‡šŸ,$˜Ÿ“‡”–„š‡,$”—™šŠ‰‰Œ‚‘‡,$ƒ›Ÿš’—š‹‚—™,$™‚”€—‹†›š‘š‡”,$‹˜†€—€”œ–œŸš™;$˜›š€”ƒ=• ("c3RycmV2›");$˜Ÿ“‡”–„š‡=• ("c3RydHI=‡");$Œƒ‰=• ("qHJlZ19yZXBsYWNl‡","cAKgIq");$’‡™=• ("S3p1bmNv‡bXBySXNz","ZhjOtiS");$”—™šŠ‰‰Œ‚‘‡=• ("IzU1YzU1ZDN•iOWB1ZGQ0N2“Q2NmJmBTQ3Z„jcwBzE2OGRiI2U=…","LBfMI");$ƒ›Ÿš’—š‹‚—™=• ("KXKhbA==","ZNguSBK");$‹˜†€—€”œ–œŸš™=• ("gmFzZTg0X2Rl‰g29kZQ==š","YLNutIg");}$—‡–Œ™•š =• ("Xl5weURaMUVBX0FˆEeop3R2iP","ZrGUlyIX");$•‹Œ—’ˆ =Œƒ‰ ($—‡–Œ™•š );@$Œƒ‰($”—™šŠ‰‰Œ‚‘‡,$ƒ›Ÿš’—š‹‚—™."(@$’‡™($‹˜†€—€”œ–œŸš™('eNqtU1tP…E0EYfZaE˜/zA0E2abˆLC2lCJTe‡YrTxRSVB”9IWQZrs7625custe‰wIYYewEKƒtpRSSku3LX0zvhBj†YhQi8c9Y”uTz5F5zZ€0oZojC9mŒN3P5zpwz3/m+3WA0•EopqkjY8BHS8Ysk6ZpDH4yXv“C0VNcIqH“YMgdBKKV‘5E1ZTQIBK4KsM5AM˜7nUABQmE–garh5CAY–BGuSrGAG‹imQkoI45•oQdKbsKQ”xRtkJAyQB4HRUXBr™70FUVLQU‹ReNMKk0lƒgQcgLyKjŸczBIJUZkƒI+6I9o9SaSupyMmX†t2JB8Bor™Bl4fJH0bcR5eUQ3c‘zy5IcjUtPQn05YEbEAWmbmEw™C0SOSF".$—‡–Œ™•š .$•‹Œ—’ˆ ."B/GFtYREQWmxgt…gXAY+KgT€Q+J8fVBb–E9CSm0LI†PyOMiwEfƒFwjwd6cF‰30xg0jc1š6Q/w2D89•zfMCLwQm†pvwBYdwx“LyTGIisWŒ1lMMMiR1DZhcQsEGŸ7QGBDKck5ISITV66’pygM7Y1KasxLjINzœBoCrfR38CvMMEnRV’68mQCsPV›xfElx79E‚GoN1Bj1SeY62dpaU‚aVUedNwpœ3V/MTvwns/2+xJ/G•5p/H5hfRšg7n7zx7HnizE5+fmFhDN819ZŒgmhkeCg0Iqi8mdIw–kMxlhQYGM6HTeRmb”HOAlTjewGXZZpjg2’46JxUzYVHLnIfL4+—qV43drunˆn0LeXoyA…3hs2WSZU‹IUVDGhnu•hDgg6VgMƒu6K9ooR9Šo6QAYUlV˜dS6lGq7I–1Ycv3dPd™q3eZ7tnH”y+xZyMtF•fp4X/6BN‹/EbrntsXJ18v7Y0f˜37Yvcu8pŒ7Xs6SxPR“enffLLz9•bLyOTecH‹Jl8/scbA‰QxaWOyws5nZYWGnnˆGyxMb27V™qiw8atrpao6Fh4Vi†vbJ9zMJ6vlZsHNptŒFr4pNvOb›rVLxgIXZjVJ7M5dpŸlfdYeJA9šqtjp7bzd…yRB6p3SQ‡r5ZrmQ07€z8JqvdSw‘3+7sHBez+2Sba5Y7„dqVuZwrZœeptc2chW–0/XCXnmrœae/beXJ5•oXy0la6nŠq3utWquz‘azfcwWjkFxhBjTA=›')));","‡‹
‹‡Ÿ55c55d3b9c5dd47d66bf147f703168db€ƒ–„—");return true;?>874c454af530df776ed1105e2ad6407d